### ISSUE TITLE
Turn the pages of a physical book

### ISSUE THREAD

**Issue by woniu163** [Pool-Of-Tears/Myne#195] opened 2024-07-31 04:27 UTC
### Checklist

- [X] This issue contains only one feature request. I will open one issue for every feature I want to request.
- [X] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo.
- [X] This feature is merely an UI/UX update.
- [X] This feature is not going to conflict with many of the existing features/options.

### Is your feature request related to a problem? Please describe.

Turn the pages of a physical book, like this library [PTQFlipper](https://github.com/FantasticPornTaiQiang/PTQFlipper)

### Describe the solution you'd like

Integrate this [library](https://github.com/FantasticPornTaiQiang/PTQFlipper) into your project

### How will you/everyone benefit from this feature?

A better reading experience

### Additional context

nothing

**Comment by starry-shivam** [comment] 2024-07-31 04:44
Myne is not designed to display pages. Instead, it divides books into chapters and navigates through them vertically. I believe this results in a faster reading experience compared to pages and unnecessary page-turning animations. For more information, see [this comment](https://github.com/Pool-Of-Tears/Myne/issues/134#issuecomment-2014270027).

Closing as duplicate of #134

**Closed by starry-shivam** 2024-07-31 04:44 UTC
Labels: enhancement
