### ISSUE TITLE
E-reading, pages move right-left.

### ISSUE THREAD

**Issue by Xoias** [Pool-Of-Tears/Myne#229] opened 2024-09-27 14:31 UTC
The application is favoulous, but in my opinion, there is only one issue preventing it to ve perfect: the reading modality.
Instead to have to scroll up and down, could it be possible to add an option to be shown in pages which could be moved swiping left and right? This is a more natural e-book experience and bettee for reading, instead to have to be scrolling down the whole time and not focusing the eyes by page.
Keep the good job!

**Comment by starry-shivam** [comment] 2024-09-27 15:24
Closing as duplicate of #221

**Closed by starry-shivam** 2024-09-27 15:24 UTC
Labels: wontfix
