### ISSUE TITLE
[Bug]: Footnotes are shown as numbers

### ISSUE THREAD

**Issue by mimi89999** [Pool-Of-Tears/Myne#207] opened 2024-09-01 19:37 UTC
### Steps to reproduce

1. Download the book from https://wolnelektury.pl/media/book/epub/lalka.epub
2. Open it in Myne

### Expected behaviour

![Screenshot_20240901-212922](https://github.com/user-attachments/assets/12eb14a4-955f-4458-bb12-3fff28857a4a)

### Actual behaviour

![Screenshot_20240901-213003](https://github.com/user-attachments/assets/79298c34-b837-4e94-9c33-c2e0bfbbbf66)

### Device name

Sony Xperia 5 V

### Android version

Android 14

### Myne version

4.0.0

**Comment by starry-shivam** [comment] 2024-09-02 04:21
I'm not sure I understand the issue. I don't know the language shown in the screenshot, but at first glance, it seems fine to me? Could you clarify what exactly the problem is that you're facing here?

**Comment by mimi89999** [comment] 2024-09-02 09:03
Please see the screenshot
![Capture d’écran du 2024-09-02 10-55-20](https://github.com/user-attachments/assets/0e4c5a52-3737-48a3-8bd0-db58e6e78bd1)
You can see that in the area marked in pink there is a blue number 2 in superscript. When I click on it, a dialog displaying the note opens
![Capture d’écran du 2024-09-02 10-55-33](https://github.com/user-attachments/assets/859eaab0-e4a6-4f0f-b953-a8ab3059d523)

Myne just adds the number `2` at the end of the word.

**Comment by starry-shivam** [comment] 2024-09-02 16:27
Myne's built-in reader does not offer advanced functionalities like that. It works by simply parsing each HTML/XHTML file inside the EPUB archive, extracting the text content, mapping it to chapters via either the `toc.ncx` file or the `<spine>` tag present in the manifest, and finally rendering the extracted text in the UI. This is why, at the very first launch, the app asks the user whether they want to use a third-party reader app of their choice, which would include all of these advanced features they expect, or if they're fine with the simple and straightforward internal reader. Your use case aligns with the former, so I'd suggest using an external reader of your choice.

Also, note that the internal reader is continuously being improved, with new functionalities and parser improvements being added in every release. It may one day become a full-fledged EPUB reader with all the functionalities of dedicated ebook reading apps. However, for now, it's mostly basic.

I'll be closing this issue since it doesn't really fit into "Bug" category.

**Closed by starry-shivam** 2024-09-02 16:27 UTC
